= Lion Chat API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[auth-and-authorization]]
== 인증 및 인가

[[token-exchange]]
=== 인증 코드로 토큰 교환

클라이언트가 OAuth2 인증 후 발급받은 임시 인증 코드를 서버에 보내 액세스 토큰과 리프레시 토큰(쿠키)을 발급받습니다.

==== 성공

operation::token_exchange_success[snippets='http-request,http-response']

[[token-refresh]]
=== 액세스 토큰 재발급

만료된 액세스 토큰을 갱신하기 위해, 쿠키에 저장된 유효한 리프레시 토큰을 사용하여 새로운 액세스 토큰을 요청합니다.

==== 성공

operation::token_refresh_success[snippets='http-request,http-response']

[[logout]]
=== 로그아웃

쿠키에 저장된 리프레시 토큰을 서버에서 무효화하고, 클라이언트의 쿠키를 삭제합니다.

==== 성공

operation::logout_success[snippets='http-request,http-response']

[[fetch-my-info]]
=== 내 정보 조회

유효한 액세스 토큰을 사용하여 현재 로그인된 사용자의 정보를 조회합니다.

==== 성공

operation::fetch_my_info_success[snippets='http-request,http-response']

==== 실패 (토큰 없음)

인증 토큰 없이 요청 시 401 Unauthorized 에러를 반환합니다.

operation::fetch_my_info_fail_no_token[snippets='http-request,http-response']

[[test-endpoints]]
== 테스트용 엔드포인트

개발 및 테스트 환경(`test` 프로필)에서만 활성화되는 API입니다.

[[test-login]]
=== 테스트용 로그인

이메일, 이름, 이미지 URL을 보내 즉시 액세스 토큰을 발급받습니다.
실제 OAuth2 인증 과정을 생략합니다.

==== 성공

operation::test_login_success[snippets='http-request,http-response']